[package]
name = "cushy_grid_test"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
cushy = { git = "https://github.com/khonsulabs/cushy", features = ["tokio-multi-thread"] }
rand = "0.8"
tokio = { version = "1", features = ["full"] }
